### ISSUE TITLE
Jakie protokoły do komunikacji holo <-> serwer <-> klient?

### ISSUE THREAD

**Issue by AdrakPro** [Hololens-PWr-Projekt/CONNECTION#3]
Między holo a serwer, raczej webRTC. 
Jakies inne pomysły? Czy hybrydowo websockety wraz z webRTC?

**Comment by aaszlii** [comment]
Według mnie chyba lepiej spróbować z websocketem wydaje się to prostsze i szybsze, ale nie mam pewności bo nigdy na tym nie pracowałam
