### ISSUE TITLE
Kiedy oraz jak dzielimy pakiet na mniejszy?

### ISSUE THREAD

**Issue by AdrakPro** [Hololens-PWr-Projekt/CONNECTION#6]
Oraz jak śledzić dany pakiet? Jakie pola dodać do struktury pakietu?

**Comment by Magouo** [comment]
Kiedy dzielimy: 

Teoretycznie Hololens nie ma limitu, przynajmniej nie znalazłem ale żeby przepustowość była dobra najlepiej gdy plik przekracza 256 KB to dzielimy go.


Jak dzielimy

Uruchamiamy serwer WebSocket, który nasłuchuje na połączenia i odbiera fragmenty danych.

Otwieramy plik binarny (obraz) w trybie odczytu (rb).

Dzielimy plik na fragmenty o rozmiarze 256 KB.

Każdy fragment jest wysyłany osobno za pomocą websocket.send(chunk).

Używamy pętli, która odczytuje plik po kawałkach i wysyła każdy fragment przez WebSocket.
